level = "collection"
layout_theme = "dark_media"

[image]
filename = "/img/john-pics/VB-John1v5b.jpg"

[[categories]]
id = "01"
image = "/img/john-pics/VB-John1v14.jpg"

[[categories]]
id = "02"
image = "/img/john-pics/VB-John13v18.jpg"

[[categories]]
id = "03"
image = "/img/john-pics/VB-John18v24.jpg"
