level = "collection"

[[categories]]
id = "01"
image = "000-01.png"

[[categories]]
id = "02"
image = "00-01c.png"

[[categories]]
id = "03"
image = "00-02d.png"

[[categories]]
id = "04"
image = "00-03a.png"

[[categories]]
id = "05"
image = "000-06.png"

[[categories]]
id = "06"
image = "42_Lk_03_03.png"

[[categories]]
id = "07"
image = "42_Lk_08_01.png"

[[categories]]
id = "08"
image = "000-07.png"

[[categories]]
id = "09"
image = "00-08a.png"

[[categories]]
id = "10"
image = "66_Re_21_01.png"
