level = "category"
id = "10"
beg = 48
count = 3

[image]
filename = "66_Re_21_01.png"

[[stories]]
id = "48"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-48-01.jpg"

[[stories]]
id = "49"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-49-01.jpg"

[[stories]]
id = "50"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-50-01.jpg"
