level = "category"
id = "07"
beg = 27
count = 9

[image]
filename = "42_Lk_08_01.png"

[[stories]]
id = "27"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-27-01.jpg"

[[stories]]
id = "28"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-28-01.jpg"

[[stories]]
id = "29"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-29-01.jpg"

[[stories]]
id = "30"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-30-01.jpg"

[[stories]]
id = "31"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-31-01.jpg"

[[stories]]
id = "32"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-32-01.jpg"

[[stories]]
id = "33"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-33-01.jpg"

[[stories]]
id = "34"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-34-01.jpg"

[[stories]]
id = "35"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-35-01.jpg"
