level = "category"
id = "09"
beg = 43
count = 5

[image]
filename = "00-08a.png"

[[stories]]
id = "43"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-43-01.jpg"

[[stories]]
id = "44"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-44-01.jpg"

[[stories]]
id = "45"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-45-01.jpg"

[[stories]]
id = "46"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-46-01.jpg"

[[stories]]
id = "47"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-47-01.jpg"
