level = "category"
id = "06"
beg = 23
count = 4

[image]
filename = "42_Lk_03_03.png"

[[stories]]
id = "23"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-23-01.jpg"

[[stories]]
id = "24"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-24-01.jpg"

[[stories]]
id = "25"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-25-01.jpg"

[[stories]]
id = "26"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-26-01.jpg"
