level = "chapter"
id = "02"

[image]
filename = "/img/john-pics/VB-John13v18.jpg"

[[stories]]
id = "13"
image = "/img/john-pics/VB-John13v18.jpg"

[[stories]]
id = "14"
image = "/img/john-pics/VB-John14v20.jpg"

[[stories]]
id = "15"
image = "/img/john-pics/VB-John15v15a.jpg"

[[stories]]
id = "16"
image = "/img/john-pics/VB-John16v25.jpg"

[[stories]]
id = "17"
image = "/img/john-pics/VB-John17v14.jpg"
