level = "chapter"
id = "01"

[image]
filename = "/img/john-pics/VB-John1v14.jpg"

[[stories]]
id = "01"
image = "/img/john-pics/VB-John1v14.jpg"

[[stories]]
id = "02"
image = "/img/john-pics/VB-John2v3.jpg"

[[stories]]
id = "03"
image = "/img/john-pics/VB-John3v2.jpg"

[[stories]]
id = "04"
image = "/img/john-pics/VB-John4v37.jpg"

[[stories]]
id = "05"
image = "/img/john-pics/VB-John5v2.jpg"

[[stories]]
id = "06"
image = "/img/john-pics/VB-John6v36.jpg"

[[stories]]
id = "07"
image = "/img/john-pics/VB-John7v28.jpg"

[[stories]]
id = "08"
image = "/img/john-pics/VB-John8v2b.jpg"

[[stories]]
id = "09"
image = "/img/john-pics/VB-John9v11b.jpg"

[[stories]]
id = "10"
image = "/img/john-pics/VB-John10v2.jpg"

[[stories]]
id = "11"
image = "/img/john-pics/VB-John11v38b-39a.jpg"

[[stories]]
id = "12"
image = "/img/john-pics/VB-John12v2b.jpg"
